### ISSUE TITLE
Error when applying project

### ISSUE THREAD

**Issue by hendpraz** [IIT-Dev/Motask#10]
SQLSTATE[42703]: Undefined column: 7 ERROR: column "id" does not exist
LINE 1: ..."created_at") values ($1, $2, $3, $4, $5, $6) returning "id"

**Comment by nicolausboby** [comment]
Solved - 
somehow migration 2019_01_13_100447_surrogate_key_to_applicants.php has never been run on production, causing column "id" not exist in the table.
